export const CHAINS_INFO = {
  "1": {
    name: "Ethereum Mainnet",
    chainID: 1,
    shortName: "eth",
    chain: "ETH",
    network: "mainnet",
    networkId: 1,
    symbol: "ETH",
    decimals: 18,
    rpc: "https://ethmainnet.anyswap.exchange",
    explorer: "https://cn.etherscan.com",
    faucets: "",
    infoURL: "https://ethereum.org",
  },
  "2": {
    name: "Expanse Network",
    chainID: 2,
    shortName: "exp",
    chain: "EXP",
    network: "mainnet",
    networkId: 1,
    symbol: "EXP",
    decimals: 18,
    rpc: "https://node.expanse.tech",
    explorer: "",
    faucets: "",
    infoURL: "https://expanse.tech",
  },
  "3": {
    name: "Ethereum Testnet Ropsten",
    chainID: 3,
    shortName: "rop",
    chain: "ETH",
    network: "ropsten",
    networkId: 3,
    symbol: "ROP",
    decimals: 18,
    rpc: "https://ropsten.infura.io/v3/${INFURA_API_KEY}",
    explorer: "",
    faucets: "https://faucet.ropsten.be?${ADDRESS}",
    infoURL: "https://github.com/ethereum/ropsten",
  },
  "4": {
    name: "Ethereum Testnet Rinkeby",
    chainID: 4,
    shortName: "rin",
    chain: "ETH",
    network: "rinkeby",
    networkId: 4,
    symbol: "RIN",
    decimals: 18,
    rpc: "https://rinkeby.infura.io/v3/${INFURA_API_KEY}",
    explorer: "https://rinkeby.etherscan.io",
    faucets: "https://faucet.rinkeby.io",
    infoURL: "https://www.rinkeby.io",
  },
  "5": {
    name: "Ethereum Testnet Görli",
    chainID: 5,
    shortName: "gor",
    chain: "ETH",
    network: "goerli",
    networkId: 5,
    symbol: "GOR",
    decimals: 18,
    rpc: "https://rpc.goerli.mudit.blog/",
    explorer: "",
    faucets: "https://goerli-faucet.slock.it/?address=${ADDRESS}",
    infoURL: "https://goerli.net/#about",
  },
  "6": {
    name: "Ethereum Classic Testnet Kotti",
    chainID: 6,
    shortName: "kot",
    chain: "ETC",
    network: "kotti",
    networkId: 6,
    symbol: "KOT",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://explorer.jade.builders/?network=kotti",
  },
  "7": {
    name: "ThaiChain",
    chainID: 7,
    shortName: "tch",
    chain: "TCH",
    network: "mainnet",
    networkId: 7,
    symbol: "TCH",
    decimals: 18,
    rpc: "https://rpc.dome.cloud",
    explorer: "",
    faucets: "",
    infoURL: "https://thaichain.io",
  },
  "8": {
    name: "Ubiq Network Mainnet",
    chainID: 8,
    shortName: "ubq",
    chain: "UBQ",
    network: "mainnet",
    networkId: 88,
    symbol: "UBQ",
    decimals: 18,
    rpc: "https://rpc.octano.dev",
    explorer: "",
    faucets: "",
    infoURL: "https://ubiqsmart.com",
  },
  "9": {
    name: "Ubiq Network Testnet",
    chainID: 9,
    shortName: "tubq",
    chain: "UBQ",
    network: "mainnet",
    networkId: 2,
    symbol: "TUBQ",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://ethersocial.org",
  },
  "10": {
    name: "Optimistic Ethereum",
    chainID: 10,
    shortName: "oeth",
    chain: "ETH",
    network: "mainnet",
    networkId: 10,
    symbol: "OETH",
    decimals: 18,
    rpc: "https://mainnet.optimism.io/",
    explorer: "",
    faucets: "",
    infoURL: "https://optimism.io",
  },
  "11": {
    name: "Metadium Mainnet",
    chainID: 11,
    shortName: "meta",
    chain: "META",
    network: "mainnet",
    networkId: 11,
    symbol: "META",
    decimals: 18,
    rpc: "https://api.metadium.com/prod",
    explorer: "",
    faucets: "",
    infoURL: "https://metadium.com",
  },
  "12": {
    name: "Metadium Testnet",
    chainID: 12,
    shortName: "kal",
    chain: "META",
    network: "testnet",
    networkId: 12,
    symbol: "KAL",
    decimals: 18,
    rpc: "https://api.metadium.com/dev",
    explorer: "",
    faucets: "",
    infoURL: "https://metadium.com",
  },
  "13": {
    name: "Diode Testnet Staging",
    chainID: 13,
    shortName: "dstg",
    chain: "DIODE",
    network: "testnet",
    networkId: 13,
    symbol: "sDIODE",
    decimals: 18,
    rpc: "https://staging.diode.io:8443/",
    explorer: "",
    faucets: "",
    infoURL: "https://diode.io/staging",
  },
  "14": {
    name: "Flare Mainnet",
    chainID: 14,
    shortName: "flr",
    chain: "FLR",
    network: "flare",
    networkId: 14,
    symbol: "FLR",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://flare.xyz",
  },
  "15": {
    name: "Diode Prenet",
    chainID: 15,
    shortName: "diode",
    chain: "DIODE",
    network: "mainnet",
    networkId: 15,
    symbol: "DIODE",
    decimals: 18,
    rpc: "https://prenet.diode.io:8443/",
    explorer: "",
    faucets: "",
    infoURL: "https://diode.io/prenet",
  },
  "16": {
    name: "Flare Testnet Coston",
    chainID: 16,
    shortName: "cflr",
    chain: "FLR",
    network: "coston",
    networkId: 16,
    symbol: "CFLR",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "https://faucet.towolabs.com",
    infoURL: "https://github.com/flare-eng/coston",
  },
  "17": {
    name: "ThaiChain 2.0 ThaiFi",
    chainID: 17,
    shortName: "tfi",
    chain: "TCH",
    network: "thaifi",
    networkId: 17,
    symbol: "TFI",
    decimals: 18,
    rpc: "https://rpc.thaifi.com",
    explorer: "",
    faucets: "",
    infoURL: "https://exp.thaifi.com",
  },
  "18": {
    name: "ThunderCore Testnet",
    chainID: 18,
    shortName: "TST",
    chain: "TST",
    network: "testnet",
    networkId: 18,
    symbol: "TST",
    decimals: 18,
    rpc: "https://testnet-rpc.thundercore.com",
    explorer: "",
    faucets: "https://faucet-testnet.thundercore.com",
    infoURL: "https://thundercore.com",
  },
  "20": {
    name: "ELA-ETH-Sidechain Mainnet",
    chainID: 20,
    shortName: "elaeth",
    chain: "ETH",
    network: "mainnet",
    networkId: 20,
    symbol: "ELA",
    decimals: 18,
    rpc: "https://mainrpc.elaeth.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.elastos.org/",
  },
  "21": {
    name: "ELA-ETH-Sidechain Testnet",
    chainID: 21,
    shortName: "elaetht",
    chain: "ETH",
    network: "testnet",
    networkId: 21,
    symbol: "tELA",
    decimals: 18,
    rpc: "https://rpc.elaeth.io",
    explorer: "",
    faucets: "https://faucet.elaeth.io/",
    infoURL: "https://elaeth.io/",
  },
  "22": {
    name: "ELA-DID-Sidechain Mainnet",
    chainID: 22,
    shortName: "eladid",
    chain: "ETH",
    network: "mainnet",
    networkId: 22,
    symbol: "ELA",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://www.elastos.org/",
  },
  "23": {
    name: "ELA-DID-Sidechain Testnet",
    chainID: 23,
    shortName: "eladidt",
    chain: "ETH",
    network: "testnet",
    networkId: 23,
    symbol: "tELA",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://elaeth.io/",
  },
  "30": {
    name: "RSK Mainnet",
    chainID: 30,
    shortName: "rsk",
    chain: "RSK",
    network: "mainnet",
    networkId: 30,
    symbol: "RBTC",
    decimals: 18,
    rpc: "https://public-node.rsk.co",
    explorer: "",
    faucets: "",
    infoURL: "https://rsk.co",
  },
  "31": {
    name: "RSK Testnet",
    chainID: 31,
    shortName: "trsk",
    chain: "RSK",
    network: "testnet",
    networkId: 31,
    symbol: "tRBTC",
    decimals: 18,
    rpc: "https://public-node.testnet.rsk.co",
    explorer: "",
    faucets: "https://faucet.testnet.rsk.co",
    infoURL: "https://rsk.co",
  },
  "33": {
    name: "GoodData Mainnet",
    chainID: 33,
    shortName: "GooD",
    chain: "GooD",
    network: "mainnet",
    networkId: 33,
    symbol: "GooD",
    decimals: 18,
    rpc: "https://rpc.goodata.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.goodata.org",
  },
  "35": {
    name: "TBWG Chain",
    chainID: 35,
    shortName: "tbwg",
    chain: "TBWG",
    network: "mainnet",
    networkId: 35,
    symbol: "TBG",
    decimals: 18,
    rpc: "https://rpc.tbwg.io",
    explorer: "",
    faucets: "",
    infoURL: "https://tbwg.io",
  },
  "38": {
    name: "Valorbit",
    chainID: 38,
    shortName: "val",
    chain: "VAL",
    network: "mainnet",
    networkId: 38,
    symbol: "VAL",
    decimals: 18,
    rpc: "https://rpc.valorbit.com/v2",
    explorer: "",
    faucets: "",
    infoURL: "https://valorbit.com",
  },
  "40": {
    name: "Telos EVM Mainnet",
    chainID: 40,
    shortName: "Telos EVM",
    chain: "TLOS",
    network: "mainnet",
    networkId: 40,
    symbol: "TLOS",
    decimals: 18,
    rpc: "https://mainnet.telos.net/evm",
    explorer: "",
    faucets: "",
    infoURL: "https://telos.net",
  },
  "41": {
    name: "Telos EVM Testnet",
    chainID: 41,
    shortName: "Telos EVM Testnet",
    chain: "TLOS",
    network: "testnet",
    networkId: 41,
    symbol: "TLOS",
    decimals: 18,
    rpc: "https://testnet.telos.net/evm",
    explorer: "",
    faucets: "https://app.telos.net/testnet/developers",
    infoURL: "https://telos.net",
  },
  "42": {
    name: "Ethereum Testnet Kovan",
    chainID: 42,
    shortName: "kov",
    chain: "ETH",
    network: "kovan",
    networkId: 42,
    symbol: "KOV",
    decimals: 18,
    rpc: "https://kovan.poa.network",
    explorer: "",
    faucets: "https://faucet.kovan.network",
    infoURL: "https://kovan-testnet.github.io/website",
  },
  "43": {
    name: "Darwinia Pangolin Testnet",
    chainID: 43,
    shortName: "darwinia",
    chain: "pangolin",
    network: "free testnet",
    networkId: 43,
    symbol: "PRING",
    decimals: 9,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://darwinia.network/",
  },
  "44": {
    name: "Darwinia Crab Network",
    chainID: 44,
    shortName: "crab",
    chain: "crab",
    network: "Crab network",
    networkId: 44,
    symbol: "CRING",
    decimals: 9,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://crab.network/",
  },
  "50": {
    name: "XinFin Network Mainnet",
    chainID: 50,
    shortName: "xdc",
    chain: "XDC",
    network: "mainnet",
    networkId: 50,
    symbol: "XDC",
    decimals: 18,
    rpc: "https://rpc.xinfin.network",
    explorer: "",
    faucets: "",
    infoURL: "https://xinfin.org",
  },
  "51": {
    name: "XinFin Apothem Testnet",
    chainID: 51,
    shortName: "TXDC",
    chain: "TXDC",
    network: "testnet",
    networkId: 51,
    symbol: "TXDC",
    decimals: 18,
    rpc: "https://rpc.apothem.network",
    explorer: "",
    faucets: "",
    infoURL: "https://xinfin.org",
  },
  "52": {
    name: "CoinEx Smart Chain Mainnet",
    chainID: 52,
    shortName: "cet",
    chain: "CSC",
    network: "mainnet",
    networkId: 52,
    symbol: "cet",
    decimals: 18,
    rpc: "https://rpc-mainnet.coinex.net",
    explorer: "",
    faucets: "",
    infoURL: "http://www.coinex.org/",
  },
  "53": {
    name: "CoinEx Smart Chain Testnet",
    chainID: 53,
    shortName: "tcet",
    chain: "CSC",
    network: "testnet",
    networkId: 53,
    symbol: "cett",
    decimals: 18,
    rpc: "https://rpc-testnet.coinex.net",
    explorer: "",
    faucets: "",
    infoURL: "http://www.coinex.org/",
  },
  "56": {
    name: "Binance Smart Chain Mainnet",
    chainID: 56,
    shortName: "bnb",
    chain: "BSC",
    network: "mainnet",
    networkId: 56,
    symbol: "BNB",
    decimals: 18,
    rpc: "https://bsc-dataseed1.binance.org",
    explorer: "https://bscscan.com",
    faucets: "",
    infoURL: "https://www.binance.org",
  },
  "60": {
    name: "GoChain",
    chainID: 60,
    shortName: "go",
    chain: "GO",
    network: "mainnet",
    networkId: 60,
    symbol: "GO",
    decimals: 18,
    rpc: "https://rpc.gochain.io",
    explorer: "",
    faucets: "",
    infoURL: "https://gochain.io",
  },
  "61": {
    name: "Ethereum Classic Mainnet",
    chainID: 61,
    shortName: "etc",
    chain: "ETC",
    network: "mainnet",
    networkId: 1,
    symbol: "ETC",
    decimals: 18,
    rpc: "https://ethereumclassic.network",
    explorer: "",
    faucets: "",
    infoURL: "https://ethereumclassic.org",
  },
  "62": {
    name: "Ethereum Classic Testnet Morden",
    chainID: 62,
    shortName: "tetc",
    chain: "ETC",
    network: "testnet",
    networkId: 2,
    symbol: "TETC",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://ethereumclassic.org",
  },
  "63": {
    name: "Ethereum Classic Testnet Mordor",
    chainID: 63,
    shortName: "metc",
    chain: "ETC",
    network: "testnet",
    networkId: 7,
    symbol: "METC",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://github.com/eth-classic/mordor/",
  },
  "64": {
    name: "Ellaism",
    chainID: 64,
    shortName: "ella",
    chain: "ELLA",
    network: "mainnet",
    networkId: 64,
    symbol: "ELLA",
    decimals: 18,
    rpc: "https://jsonrpc.ellaism.org",
    explorer: "",
    faucets: "",
    infoURL: "https://ellaism.org",
  },
  "65": {
    name: "OKExChain Testnet",
    chainID: 65,
    shortName: "tokt",
    chain: "okexchain",
    network: "testnet",
    networkId: 65,
    symbol: "OKT",
    decimals: 18,
    rpc: "https://exchaintestrpc.okex.org",
    explorer: "https://www.oklink.com/okexchain-test",
    faucets: "https://www.okex.com/drawdex",
    infoURL: "https://www.okex.com/okexchain",
  },
  "66": {
    name: "OKExChain Mainnet",
    chainID: 66,
    shortName: "okt",
    chain: "okexchain",
    network: "mainnet",
    networkId: 66,
    symbol: "OKT",
    decimals: 18,
    rpc: "https://exchainrpc.okex.org",
    explorer: "https://www.oklink.com/okexchain",
    faucets: "",
    infoURL: "https://www.okex.com/okexchain",
  },
  "67": {
    name: "DBChain Testnet",
    chainID: 67,
    shortName: "dbm",
    chain: "DBM",
    network: "testnet",
    networkId: 67,
    symbol: "DBM",
    decimals: 18,
    rpc: "http://test-rpc.dbmbp.com",
    explorer: "",
    faucets: "",
    infoURL: "http://test.dbmbp.com",
  },
  "68": {
    name: "SoterOne Mainnet",
    chainID: 68,
    shortName: "SO1",
    chain: "SOTER",
    network: "mainnet",
    networkId: 68,
    symbol: "SOTER",
    decimals: 18,
    rpc: "https://rpc.soter.one",
    explorer: "",
    faucets: "",
    infoURL: "https://www.soterone.com",
  },
  "69": {
    name: "Optimistic Ethereum Testnet Kovan",
    chainID: 69,
    shortName: "okov",
    chain: "ETH",
    network: "kovan",
    networkId: 69,
    symbol: "KOR",
    decimals: 18,
    rpc: "https://kovan.optimism.io/",
    explorer: "",
    faucets: "",
    infoURL: "https://optimism.io",
  },
  "70": {
    name: "HOO Smart Chain Mainnet",
    chainID: 70,
    shortName: "hoosmartchain",
    chain: "ETH",
    network: "mainnet",
    networkId: 70,
    symbol: "HOO",
    decimals: 18,
    rpc: "https://http-mainnet.hoosmartchain.com",
    explorer: "https://www.hscscan.com",
    faucets: "",
    infoURL: "https://www.hoosmartchain.com",
  },
  "76": {
    name: "Mix",
    chainID: 76,
    shortName: "mix",
    chain: "MIX",
    network: "mainnet",
    networkId: 76,
    symbol: "MIX",
    decimals: 18,
    rpc: "https://rpc2.mix-blockchain.org:8647",
    explorer: "",
    faucets: "",
    infoURL: "https://mix-blockchain.org",
  },
  "77": {
    name: "POA Network Sokol",
    chainID: 77,
    shortName: "poa",
    chain: "POA",
    network: "sokol",
    networkId: 77,
    symbol: "POA",
    decimals: 18,
    rpc: "https://sokol.poa.network",
    explorer: "",
    faucets: "https://faucet-sokol.herokuapp.com",
    infoURL: "https://poa.network",
  },
  "78": {
    name: "PrimusChain mainnet",
    chainID: 78,
    shortName: "primuschain",
    chain: "PC",
    network: "mainnet",
    networkId: 78,
    symbol: "PETH",
    decimals: 18,
    rpc: "https://ethnode.primusmoney.com/mainnet",
    explorer: "",
    faucets: "",
    infoURL: "https://primusmoney.com",
  },
  "80": {
    name: "GeneChain",
    chainID: 80,
    shortName: "GeneChain",
    chain: "GeneChain",
    network: "mainnet",
    networkId: 80,
    symbol: "RNA",
    decimals: 18,
    rpc: "https://rpc.genechain.io",
    explorer: "https://scan.genechain.io",
    faucets: "",
    infoURL: "https://scan.genechain.io/",
  },
  "82": {
    name: "Meter Mainnet",
    chainID: 82,
    shortName: "Meter",
    chain: "METER",
    network: "mainnet",
    networkId: 82,
    symbol: "MTR",
    decimals: 18,
    rpc: "https://rpc.meter.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.meter.io",
  },
  "85": {
    name: "GateChain Testnet",
    chainID: 85,
    shortName: "GTC-T",
    chain: "gatechain",
    network: "testnet",
    networkId: 85,
    symbol: "GT",
    decimals: 18,
    rpc: "https://testnet.gatenode.cc",
    explorer: "https://www.gatescan.org/testnet",
    faucets: "https://www.gatescan.org/testnet/faucet",
    infoURL: "https://www.gatechain.io",
  },
  "86": {
    name: "GateChain Mainnet",
    chainID: 86,
    shortName: "GTC",
    chain: "gatechain",
    network: "mainnet",
    networkId: 86,
    symbol: "GT",
    decimals: 18,
    rpc: "https://evm.gatenode.cc",
    explorer: "https://www.gatescan.org",
    faucets: "https://www.gatescan.org/faucet",
    infoURL: "https://www.gatechain.io",
  },
  "88": {
    name: "TomoChain",
    chainID: 88,
    shortName: "tomo",
    chain: "TOMO",
    network: "mainnet",
    networkId: 88,
    symbol: "TOMO",
    decimals: 18,
    rpc: "https://rpc.tomochain.com",
    explorer: "",
    faucets: "",
    infoURL: "https://tomocoin.io",
  },
  "95": {
    name: "CryptoKylin Testnet",
    chainID: 95,
    shortName: "Kylin Testnet",
    chain: "EOS",
    network: "testnet",
    networkId: 95,
    symbol: "EOS",
    decimals: 18,
    rpc: "https://kylin.eosargentina.io",
    explorer: "https://kylin.eosargentina.io",
    faucets: "",
    infoURL: "https://www.cryptokylin.io/",
  },
  "97": {
    name: "Binance Smart Chain Testnet",
    chainID: 97,
    shortName: "bnbt",
    chain: "BSC",
    network: "Chapel",
    networkId: 97,
    symbol: "tBNB",
    decimals: 18,
    rpc: "https://data-seed-prebsc-1-s1.binance.org:8545",
    explorer: "https://testnet.bscscan.com",
    faucets: "https://testnet.binance.org/faucet-smart",
    infoURL: "https://testnet.binance.org/",
  },
  "99": {
    name: "POA Network Core",
    chainID: 99,
    shortName: "skl",
    chain: "POA",
    network: "core",
    networkId: 99,
    symbol: "SKL",
    decimals: 18,
    rpc: "https://core.poanetwork.dev",
    explorer: "",
    faucets: "",
    infoURL: "https://poa.network",
  },
  "100": {
    name: "xDAI Chain",
    chainID: 100,
    shortName: "xdai",
    chain: "XDAI",
    network: "mainnet",
    networkId: 100,
    symbol: "xDAI",
    decimals: 18,
    rpc: "https://rpc.xdaichain.com",
    explorer: "",
    faucets: "",
    infoURL: "https://forum.poa.network/c/xdai-chain",
  },
  "101": {
    name: "EtherInc",
    chainID: 101,
    shortName: "eti",
    chain: "ETI",
    network: "mainnet",
    networkId: 1,
    symbol: "ETI",
    decimals: 18,
    rpc: "https://api.einc.io/jsonrpc/mainnet",
    explorer: "",
    faucets: "",
    infoURL: "https://einc.io",
  },
  "102": {
    name: "Web3Games Testnet",
    chainID: 102,
    shortName: "w3g",
    chain: "Web3Games",
    network: "testnet",
    networkId: 102,
    symbol: "W3G",
    decimals: 18,
    rpc: "https://substrate.org.cn",
    explorer: "",
    faucets: "",
    infoURL: "https://web3games.org/",
  },
  "108": {
    name: "ThunderCore Mainnet",
    chainID: 108,
    shortName: "TT",
    chain: "TT",
    network: "mainnet",
    networkId: 108,
    symbol: "TT",
    decimals: 18,
    rpc: "https://mainnet-rpc.thundercore.com",
    explorer: "",
    faucets: "https://faucet.thundercore.com",
    infoURL: "https://thundercore.com",
  },
  "110": {
    name: "Proton Testnet",
    chainID: 110,
    shortName: "xpr",
    chain: "XPR",
    network: "testnet",
    networkId: 110,
    symbol: "XPR",
    decimals: 4,
    rpc: "https://protontestnet.greymass.com/",
    explorer: "",
    faucets: "",
    infoURL: "https://protonchain.com",
  },
  "111": {
    name: "EtherLite Chain",
    chainID: 111,
    shortName: "ETL",
    chain: "ETL",
    network: "mainnet",
    networkId: 111,
    symbol: "ETL",
    decimals: 18,
    rpc: "https://rpc.etherlite.org",
    explorer: "",
    faucets: "https://etherlite.org/faucets",
    infoURL: "https://etherlite.org",
  },
  "122": {
    name: "Fuse Mainnet",
    chainID: 122,
    shortName: "fuse",
    chain: "FUSE",
    network: "mainnet",
    networkId: 122,
    symbol: "FUSE",
    decimals: 18,
    rpc: "https://rpc.fuse.io",
    explorer: "",
    faucets: "",
    infoURL: "https://fuse.io/",
  },
  "127": {
    name: "Factory 127 Mainnet",
    chainID: 127,
    shortName: "feth",
    chain: "FETH",
    network: "factory127 mainnet",
    networkId: 127,
    symbol: "FETH",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://www.factory127.com",
  },
  "128": {
    name: "Huobi ECO Chain Mainnet",
    chainID: 128,
    shortName: "heco",
    chain: "Heco",
    network: "mainnet",
    networkId: 128,
    symbol: "HT",
    decimals: 18,
    rpc: "https://http-mainnet-node1.hecochain.com",
    explorer: "https://hecoinfo.com/",
    faucets: "",
    infoURL: "https://hecoinfo.com",
  },
  "137": {
    name: "Matic Mainnet",
    chainID: 137,
    shortName: "matic",
    chain: "Matic",
    network: "mainnet",
    networkId: 137,
    symbol: "MATIC",
    decimals: 18,
    rpc: "https://rpc-mainnet.matic.network",
    explorer: "https://polygonscan.com",
    faucets: "",
    infoURL: "https://matic.network/",
  },
  "162": {
    name: "Lightstreams Testnet",
    chainID: 162,
    shortName: "tpht",
    chain: "PHT",
    network: "sirius",
    networkId: 162,
    symbol: "PHT",
    decimals: 18,
    rpc: "https://node.sirius.lightstreams.io",
    explorer: "",
    faucets: "https://discuss.lightstreams.network/t/request-test-tokens",
    infoURL: "https://explorer.sirius.lightstreams.io",
  },
  "163": {
    name: "Lightstreams Mainnet",
    chainID: 163,
    shortName: "pht",
    chain: "PHT",
    network: "mainnet",
    networkId: 163,
    symbol: "PHT",
    decimals: 18,
    rpc: "https://node.mainnet.lightstreams.io",
    explorer: "",
    faucets: "",
    infoURL: "https://explorer.lightstreams.io",
  },
  "170": {
    name: "HOO Smart Chain Testnet",
    chainID: 170,
    shortName: "hoosmartchain",
    chain: "ETH",
    network: "testnet",
    networkId: 170,
    symbol: "HOO",
    decimals: 18,
    rpc: "https://http-testnet.hoosmartchain.com",
    explorer: "https://testnet.hscscan.com",
    faucets: "https://testnet.hscscan.com/hydrant",
    infoURL: "https://www.hoosmartchain.com",
  },
  "211": {
    name: "Freight Trust Network",
    chainID: 211,
    shortName: "EDI",
    chain: "EDI",
    network: "freight & trade network",
    networkId: 0,
    symbol: "0xF",
    decimals: 18,
    rpc: "http://13.57.207.168:3435",
    explorer: "",
    faucets: "http://faucet.freight.sh",
    infoURL: "https://freighttrust.com",
  },
  "246": {
    name: "Energy Web Chain",
    chainID: 246,
    shortName: "ewt",
    chain: "Energy Web Chain",
    network: "mainnet",
    networkId: 246,
    symbol: "EWT",
    decimals: 18,
    rpc: "https://rpc.energyweb.org",
    explorer: "",
    faucets: "https://faucet.carbonswap.exchange",
    infoURL: "https://energyweb.org",
  },
  "250": {
    name: "Fantom Opera",
    chainID: 250,
    shortName: "ftm",
    chain: "FTM",
    network: "mainnet",
    networkId: 250,
    symbol: "FTM",
    decimals: 18,
    rpc: "https://rpcapi.fantom.network",
    explorer: "https://ftmscan.com",
    faucets: "",
    infoURL: "https://fantom.foundation",
  },
  "256": {
    name: "Huobi ECO Chain Testnet",
    chainID: 256,
    shortName: "hecot",
    chain: "Heco",
    network: "testnet",
    networkId: 256,
    symbol: "HT",
    decimals: 18,
    rpc: "https://http-testnet.hecochain.com",
    explorer: "https://testnet.hecoinfo.com/",
    faucets: "https://testnet.hscscan.com/hydrant",
    infoURL: "https://testnet.hecoinfo.com",
  },
  "269": {
    name: "High Performance Blockchain",
    chainID: 269,
    shortName: "hpb",
    chain: "HPB",
    network: "mainnet",
    networkId: 100,
    symbol: "HPB",
    decimals: 18,
    rpc: "https://hpb.app",
    explorer: "",
    faucets: "",
    infoURL: "https://hpbscan.org/",
  },
  "321": {
    name: "KuCoin Community Chain Mainnet",
    chainID: 321,
    shortName: "kcs",
    chain: "KCC",
    network: "mainnet",
    networkId: 321,
    symbol: "KCS",
    decimals: 18,
    rpc: "https://rpc-mainnet.kcc.network",
    explorer: "https://explorer.kcc.io/en",
    faucets: "",
    infoURL: "https://kcc.io",
  },
  "322": {
    name: "KuCoin Community Chain Testnet",
    chainID: 322,
    shortName: "kcst",
    chain: "KCC",
    network: "testnet",
    networkId: 322,
    symbol: "tKCS",
    decimals: 18,
    rpc: "https://rpc-testnet.kcc.network",
    explorer: "https://scan-testnet.kcc.network",
    faucets: "https://faucet-testnet.kcc.network",
    infoURL: "https://scan-testnet.kcc.network",
  },
  "385": {
    name: "Lisinski",
    chainID: 385,
    shortName: "lisinski",
    chain: "CRO",
    network: "mainnet",
    networkId: 385,
    symbol: "LISINSKI",
    decimals: 18,
    rpc: "https://rpc-bitfalls1.lisinski.online",
    explorer: "",
    faucets: "https://pipa.lisinski.online",
    infoURL: "https://lisinski.online",
  },
  "420": {
    name: "Optimistic Ethereum Testnet Goerli",
    chainID: 420,
    shortName: "ogor",
    chain: "ETH",
    network: "goerli",
    networkId: 420,
    symbol: "GOR",
    decimals: 18,
    rpc: "https://goerli.optimism.io/",
    explorer: "",
    faucets: "",
    infoURL: "https://optimism.io",
  },
  "499": {
    name: "Rupaya",
    chainID: 499,
    shortName: "rupx",
    chain: "RUPX",
    network: "mainnet",
    networkId: 499,
    symbol: "RUPX",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://www.rupx.io",
  },
  "558": {
    name: "Tao Network",
    chainID: 558,
    shortName: "tao",
    chain: "TAO",
    network: "core",
    networkId: 558,
    symbol: "TAO",
    decimals: 18,
    rpc: "https://rpc.testnet.tao.network",
    explorer: "",
    faucets: "",
    infoURL: "https://tao.network",
  },
  "595": {
    name: "Acala Mandala Testnet",
    chainID: 595,
    shortName: "maca",
    chain: "mACA",
    network: "testnet",
    networkId: 595,
    symbol: "mACA",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://acala.network",
  },
  "686": {
    name: "Karura Network",
    chainID: 686,
    shortName: "kar",
    chain: "KAR",
    network: "mainnet",
    networkId: 686,
    symbol: "KAR",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://karura.network",
  },
  "721": {
    name: "Factory 127 Testnet",
    chainID: 721,
    shortName: "tfeth",
    chain: "FETH",
    network: "factory127 testnet",
    networkId: 721,
    symbol: "FETH",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://www.factory127.com",
  },
  "777": {
    name: "Ethermint Testnet",
    chainID: 777,
    shortName: "emint",
    chain: "ETHERMINT",
    network: "testnet",
    networkId: 777,
    symbol: "Photon",
    decimals: 18,
    rpc: "http://54.210.246.165:8545",
    explorer: "",
    faucets: "",
    infoURL: "https://docs.ethermint.zone",
  },
  "787": {
    name: "Acala Network",
    chainID: 787,
    shortName: "aca",
    chain: "ACA",
    network: "mainnet",
    networkId: 787,
    symbol: "ACA",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://acala.network",
  },
  "803": {
    name: "Haic",
    chainID: 803,
    shortName: "haic",
    chain: "Haic",
    network: "mainnet",
    networkId: 803,
    symbol: "HAIC",
    decimals: 18,
    rpc: "https://orig.haichain.io/",
    explorer: "",
    faucets: "",
    infoURL: "https://www.haichain.io/",
  },
  "820": {
    name: "Callisto Mainnet",
    chainID: 820,
    shortName: "clo",
    chain: "CLO",
    network: "mainnet",
    networkId: 1,
    symbol: "CLO",
    decimals: 18,
    rpc: "https://clo-geth.0xinfra.com",
    explorer: "",
    faucets: "",
    infoURL: "https://callisto.network",
  },
  "821": {
    name: "Callisto Testnet",
    chainID: 821,
    shortName: "tclo",
    chain: "CLO",
    network: "testnet",
    networkId: 2,
    symbol: "TCLO",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://callisto.network",
  },
  "888": {
    name: "Wanchain",
    chainID: 888,
    shortName: "wan",
    chain: "WAN",
    network: "mainnet",
    networkId: 888,
    symbol: "WAN",
    decimals: 18,
    rpc: "https://gwan-ssl.wandevs.org:56891/",
    explorer: "",
    faucets: "",
    infoURL: "https://www.wanscan.org",
  },
  "977": {
    name: "Nepal Blockchain Network",
    chainID: 977,
    shortName: "yeti",
    chain: "YETI",
    network: "mainnet",
    networkId: 977,
    symbol: "YETI",
    decimals: 18,
    rpc: "https://api.nepalblockchain.dev",
    explorer: "",
    faucets: "https://faucet.nepalblockchain.network",
    infoURL: "https://nepalblockchain.network",
  },
  "999": {
    name: "Wanchain Testnet",
    chainID: 999,
    shortName: "twan",
    chain: "WAN",
    network: "testnet",
    networkId: 999,
    symbol: "WAN",
    decimals: 18,
    rpc: "https://gwan-ssl.wandevs.org:46891/",
    explorer: "",
    faucets: "",
    infoURL: "https://testnet.wanscan.org",
  },
  "1001": {
    name: "Klaytn Testnet Baobab",
    chainID: 1001,
    shortName: "Baobab",
    chain: "KLAY",
    network: "baobab",
    networkId: 1001,
    symbol: "KLAY",
    decimals: 18,
    rpc: "https://node-api.klaytnapi.com/v1/klaytn",
    explorer: "",
    faucets: "https://baobab.wallet.klaytn.com/access?next=faucet",
    infoURL: "https://www.klaytn.com/",
  },
  "1007": {
    name: "Newton Testnet",
    chainID: 1007,
    shortName: "tnew",
    chain: "NEW",
    network: "testnet",
    networkId: 1007,
    symbol: "NEW",
    decimals: 18,
    rpc: "https://rpc1.newchain.newtonproject.org",
    explorer: "",
    faucets: "",
    infoURL: "https://www.newtonproject.org/",
  },
  "1010": {
    name: "Evrice Network",
    chainID: 1010,
    shortName: "EVC",
    chain: "EVC",
    network: "Evrice",
    networkId: 1010,
    symbol: "EVC",
    decimals: 18,
    rpc: "https://meta.evrice.com",
    explorer: "",
    faucets: "",
    infoURL: "https://evrice.com",
  },
  "1012": {
    name: "Newton",
    chainID: 1012,
    shortName: "new",
    chain: "NEW",
    network: "mainnet",
    networkId: 1012,
    symbol: "NEW",
    decimals: 18,
    rpc: "https://global.rpc.mainnet.newtonproject.org",
    explorer: "",
    faucets: "",
    infoURL: "https://www.newtonproject.org/",
  },
  "1022": {
    name: "Sakura",
    chainID: 1022,
    shortName: "sku",
    chain: "Sakura",
    network: "sakura",
    networkId: 1022,
    symbol: "SKU",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://clover.finance/sakura",
  },
  "1023": {
    name: "Clover Testnet",
    chainID: 1023,
    shortName: "tclv",
    chain: "Clover",
    network: "clover testnet",
    networkId: 1023,
    symbol: "CLV",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://clover.finance",
  },
  "1024": {
    name: "Clover Mainnet",
    chainID: 1024,
    shortName: "clv",
    chain: "Clover",
    network: "clover mainnet",
    networkId: 1024,
    symbol: "CLV",
    decimals: 18,
    rpc: "https://rpc-ivy.clover.finance",
    explorer: "",
    faucets: "",
    infoURL: "https://clover.finance",
  },
  "1139": {
    name: "MathChain",
    chainID: 1139,
    shortName: "MATH",
    chain: "MATH",
    network: "mainnet",
    networkId: 1139,
    symbol: "MATH",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://mathchain.org",
  },
  "1140": {
    name: "MathChain Testnet",
    chainID: 1140,
    shortName: "tMATH",
    chain: "MATH",
    network: "testnet",
    networkId: 1140,
    symbol: "MATH",
    decimals: 18,
    rpc: "https://galois-hk.maiziqianbao.net/rpc",
    explorer: "",
    faucets: "https://scan.boka.network/#/Galois/faucet",
    infoURL: "https://mathchain.org",
  },
  "1284": {
    name: "Moonbeam Polkadot",
    chainID: 1284,
    shortName: "mbeam",
    chain: "MOON",
    network: "moonbeam",
    networkId: 1284,
    symbol: "GLMR",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://moonbeam.network/networks/moonbeam/",
  },
  "1285": {
    name: "Moonriver Kusama",
    chainID: 1285,
    shortName: "mriver",
    chain: "MOON",
    network: "moonriver",
    networkId: 1285,
    symbol: "RIVER",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://moonbeam.network/networks/moonriver/",
  },
  "1286": {
    name: "Moonrock Rococo",
    chainID: 1286,
    shortName: "mrock",
    chain: "MOON",
    network: "moonrock",
    networkId: 1286,
    symbol: "ROC",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "",
  },
  "1287": {
    name: "Moonbeam Testnet Moonbase Alpha",
    chainID: 1287,
    shortName: "mbase",
    chain: "MOON",
    network: "moonbase",
    networkId: 1287,
    symbol: "DEV",
    decimals: 18,
    rpc: "https://rpc.testnet.moonbeam.network",
    explorer: "",
    faucets: "",
    infoURL: "https://docs.moonbeam.network/networks/testnet/",
  },
  "1618": {
    name: "Catecoin Chain Mainnet",
    chainID: 1618,
    shortName: "cate",
    chain: "Catechain",
    network: "mainnet",
    networkId: 1618,
    symbol: "CATE",
    decimals: 18,
    rpc: "https://send.catechain.com",
    explorer: "",
    faucets: "",
    infoURL: "https://catechain.com",
  },
  "1620": {
    name: "Atheios",
    chainID: 1620,
    shortName: "ath",
    chain: "ATH",
    network: "mainnet",
    networkId: 11235813,
    symbol: "ATH",
    decimals: 18,
    rpc: "https://wallet.atheios.com:8797",
    explorer: "",
    faucets: "",
    infoURL: "https://atheios.com",
  },
  "1856": {
    name: "Teslafunds",
    chainID: 1856,
    shortName: "tsf",
    chain: "TSF",
    network: "mainnet",
    networkId: 1,
    symbol: "TSF",
    decimals: 18,
    rpc: "https://tsfapi.europool.me",
    explorer: "",
    faucets: "",
    infoURL: "https://teslafunds.io",
  },
  "1987": {
    name: "EtherGem",
    chainID: 1987,
    shortName: "egem",
    chain: "EGEM",
    network: "mainnet",
    networkId: 1987,
    symbol: "EGEM",
    decimals: 18,
    rpc: "https://jsonrpc.egem.io/custom",
    explorer: "",
    faucets: "",
    infoURL: "https://egem.io",
  },
  "2020": {
    name: "420coin",
    chainID: 2020,
    shortName: "420",
    chain: "420",
    network: "mainnet",
    networkId: 2020,
    symbol: "420",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://420integrated.com",
  },
  "2021": {
    name: "Edgeware Mainnet",
    chainID: 2021,
    shortName: "edg",
    chain: "EDG",
    network: "mainnet",
    networkId: 2021,
    symbol: "EDG",
    decimals: 18,
    rpc: "https://mainnet1.edgewa.re",
    explorer: "",
    faucets: "",
    infoURL: "http://edgewa.re",
  },
  "2022": {
    name: "Beresheet Testnet",
    chainID: 2022,
    shortName: "edgt",
    chain: "EDG",
    network: "beresheet",
    networkId: 2022,
    symbol: "tEDG",
    decimals: 18,
    rpc: "https://beresheet1.edgewa.re",
    explorer: "",
    faucets: "",
    infoURL: "http://edgewa.re",
  },
  "4689": {
    name: "IoTeX Network Mainnet",
    chainID: 4689,
    shortName: "iotex-mainnet",
    chain: "iotex.io",
    network: "mainnet",
    networkId: 4689,
    symbol: "IOTX",
    decimals: 18,
    rpc: "https://babel-api.mainnet.iotex.io",
    explorer: "",
    faucets: "",
    infoURL: "https://iotex.io",
  },
  "4690": {
    name: "IoTeX Network Testnet",
    chainID: 4690,
    shortName: "iotex-testnet",
    chain: "iotex.io",
    network: "testnet",
    networkId: 4690,
    symbol: "IOTX",
    decimals: 18,
    rpc: "https://babel-api.testnet.iotex.io",
    explorer: "",
    faucets: "https://faucet.iotex.io/",
    infoURL: "https://iotex.io",
  },
  "5197": {
    name: "EraSwap Mainnet",
    chainID: 5197,
    shortName: "es",
    chain: "ESN",
    network: "mainnet",
    networkId: 5197,
    symbol: "ES",
    decimals: 18,
    rpc: "https://mainnet.eraswap.network",
    explorer: "",
    faucets: "",
    infoURL: "https://eraswap.info/",
  },
  "5869": {
    name: "Wegochain Rubidium Mainnet",
    chainID: 5869,
    shortName: "rbd",
    chain: "RBD",
    network: "mainnet",
    networkId: 5869,
    symbol: "RBD",
    decimals: 18,
    rpc: "https://proxy.wegochain.io",
    explorer: "",
    faucets: "",
    infoURL: "http://wegochain.io",
  },
  "8029": {
    name: "MDGL Testnet",
    chainID: 8029,
    shortName: "mdgl",
    chain: "MDGL",
    network: "testnet",
    networkId: 8029,
    symbol: "MDGLT",
    decimals: 18,
    rpc: "https://testnet.mdgl.io",
    explorer: "",
    faucets: "",
    infoURL: "https://mdgl.io",
  },
  "8080": {
    name: "GeneChain Adenine Testnet",
    chainID: 8080,
    shortName: "GeneChainAdn",
    chain: "GeneChain",
    network: "adenine",
    networkId: 8080,
    symbol: "tRNA",
    decimals: 18,
    rpc: "https://rpc-testnet.genechain.io",
    explorer: "https://scan-testnet.genechain.io",
    faucets: "https://faucet.genechain.io",
    infoURL: "https://scan-testnet.genechain.io/",
  },
  "8217": {
    name: "Klaytn Mainnet Cypress",
    chainID: 8217,
    shortName: "Cypress",
    chain: "KLAY",
    network: "cypress",
    networkId: 8217,
    symbol: "KLAY",
    decimals: 18,
    rpc: "https://node-api.klaytnapi.com/v1/klaytn",
    explorer: "",
    faucets: "",
    infoURL: "https://www.klaytn.com/",
  },
  "8285": {
    name: "KorthoTest",
    chainID: 8285,
    shortName: "Kortho",
    chain: "Kortho",
    network: "Test",
    networkId: 8285,
    symbol: "KTO",
    decimals: 11,
    rpc: "https://www.krotho-test.net",
    explorer: "",
    faucets: "",
    infoURL: "https://www.kortho.io/",
  },
  "8724": {
    name: "TOOL Global Testnet",
    chainID: 8724,
    shortName: "olo",
    chain: "OLO",
    network: "testnet",
    networkId: 8724,
    symbol: "OLO",
    decimals: 18,
    rpc: "https://testnet-web3.wolot.io",
    explorer: "",
    faucets: "https://testnet-explorer.wolot.io",
    infoURL: "https://testnet-explorer.wolot.io",
  },
  "8995": {
    name: "bloxberg",
    chainID: 8995,
    shortName: "berg",
    chain: "bloxberg",
    network: "mainnet",
    networkId: 8995,
    symbol: "U+25B3",
    decimals: 18,
    rpc: "https://core.bloxberg.org",
    explorer: "",
    faucets: "https://faucet.bloxberg.org/",
    infoURL: "https://bloxberg.org",
  },
  "10000": {
    name: "Smart Bitcoin Cash",
    chainID: 10000,
    shortName: "smartbch",
    chain: "smartBCH",
    network: "mainnet",
    networkId: 10000,
    symbol: "BCH",
    decimals: 18,
    rpc: "https://rpc-mainnet.smartbch.org",
    explorer: "",
    faucets: "",
    infoURL: "http://smartbch.org/",
  },
  "10001": {
    name: "Smart Bitcoin Cash Testnet",
    chainID: 10001,
    shortName: "smartbchtest",
    chain: "smartBCHTest",
    network: "testnet",
    networkId: 10001,
    symbol: "BCHT",
    decimals: 18,
    rpc: "https://rpc-testnet.smartbch.org",
    explorer: "",
    faucets: "",
    infoURL: "http://smartbch.org/",
  },
  "10101": {
    name: "Blockchain Genesis Mainnet",
    chainID: 10101,
    shortName: "GEN",
    chain: "GEN",
    network: "mainnet",
    networkId: 10101,
    symbol: "GEN",
    decimals: 18,
    rpc: "https://eu.mainnet.xixoio.com",
    explorer: "",
    faucets: "",
    infoURL: "https://www.xixoio.com/",
  },
  "24484": {
    name: "Webchain",
    chainID: 24484,
    shortName: "web",
    chain: "WEB",
    network: "mainnet",
    networkId: 37129,
    symbol: "WEB",
    decimals: 18,
    rpc: "https://node1.webchain.network",
    explorer: "",
    faucets: "",
    infoURL: "https://webchain.network",
  },
  "24734": {
    name: "MintMe.com Coin",
    chainID: 24734,
    shortName: "mintme",
    chain: "MINTME",
    network: "mainnet",
    networkId: 37480,
    symbol: "MINTME",
    decimals: 18,
    rpc: "https://node1.mintme.com",
    explorer: "",
    faucets: "",
    infoURL: "https://www.mintme.com",
  },
  "31102": {
    name: "Ethersocial Network",
    chainID: 31102,
    shortName: "esn",
    chain: "ESN",
    network: "mainnet",
    networkId: 1,
    symbol: "ESN",
    decimals: 18,
    rpc: "https://api.esn.gonspool.com",
    explorer: "",
    faucets: "",
    infoURL: "https://ethersocial.org",
  },
  "32659": {
    name: "Fusion Mainnet",
    chainID: 32659,
    shortName: "fsn",
    chain: "FSN",
    network: "mainnet",
    networkId: 32659,
    symbol: "FSN",
    decimals: 18,
    rpc: "https://mainnet.anyswap.exchange",
    explorer: "",
    faucets: "",
    infoURL: "https://www.fusion.org/",
  },
  "39797": {
    name: "Energi Mainnet",
    chainID: 39797,
    shortName: "nrg",
    chain: "NRG",
    network: "mainnet",
    networkId: 39797,
    symbol: "NRG",
    decimals: 18,
    rpc: "https://nodeapi.gen3.energi.network",
    explorer: "",
    faucets: "",
    infoURL: "https://www.energi.world/",
  },
  "42069": {
    name: "pegglecoin",
    chainID: 42069,
    shortName: "PC",
    chain: "42069",
    network: "mainnet",
    networkId: 42069,
    symbol: "peggle",
    decimals: 18,
    rpc: "",
    explorer: "",
    faucets: "",
    infoURL: "https://teampeggle.com",
  },
  "42220": {
    name: "Celo Mainnet",
    chainID: 42220,
    shortName: "CELO",
    chain: "CELO",
    network: "Mainnet",
    networkId: 42220,
    symbol: "CELO",
    decimals: 18,
    rpc: "https://forno.celo.org",
    explorer: "",
    faucets: "",
    infoURL: "https://docs.celo.org/",
  },
  "43110": {
    name: "Athereum",
    chainID: 43110,
    shortName: "avaeth",
    chain: "ATH",
    network: "athereum",
    networkId: 43110,
    symbol: "ATH",
    decimals: 18,
    rpc: "https://ava.network:21015/ext/evm/rpc",
    explorer: "",
    faucets: "http://athfaucet.ava.network//?address=${ADDRESS}",
    infoURL: "https://athereum.ava.network",
  },
  "43113": {
    name: "Avalanche Fuji Testnet",
    chainID: 43113,
    shortName: "Fuji",
    chain: "AVAX",
    network: "testnet",
    networkId: 1,
    symbol: "AVAX",
    decimals: 18,
    rpc: "https://api.avax-test.network/ext/bc/C/rpc",
    explorer: "",
    faucets: "https://faucet.avax-test.network/",
    infoURL: "https://cchain.explorer.avax-test.network",
  },
  "43114": {
    name: "Avalanche Mainnet",
    chainID: 43114,
    shortName: "Avalanche",
    chain: "AVAX",
    network: "mainnet",
    networkId: 1,
    symbol: "AVAX",
    decimals: 18,
    rpc: "https://api.avax.network/ext/bc/C/rpc",
    explorer: "",
    faucets: "",
    infoURL: "https://cchain.explorer.avax.network/",
  },
  "44787": {
    name: "Celo Alfajores Testnet",
    chainID: 44787,
    shortName: "ALFA",
    chain: "CELO",
    network: "Alfajores",
    networkId: 44787,
    symbol: "CELO",
    decimals: 18,
    rpc: "https://alfajores-forno.celo-testnet.org",
    explorer: "",
    faucets: "https://celo.org/developers/faucet",
    infoURL: "https://docs.celo.org/",
  },
  "49797": {
    name: "Energi Testnet",
    chainID: 49797,
    shortName: "tnrg",
    chain: "NRG",
    network: "testnet",
    networkId: 49797,
    symbol: "tNRG",
    decimals: 18,
    rpc: "https://nodeapi.test3.energi.network",
    explorer: "",
    faucets: "",
    infoURL: "https://www.energi.world/",
  },
  "62320": {
    name: "Celo Baklava Testnet",
    chainID: 62320,
    shortName: "BKLV",
    chain: "CELO",
    network: "Baklava",
    networkId: 62320,
    symbol: "CELO",
    decimals: 18,
    rpc: "https://baklava-forno.celo-testnet.org",
    explorer: "",
    faucets:
      "https://docs.google.com/forms/d/e/1FAIpQLSdfr1BwUTYepVmmvfVUDRCwALejZ-TUva2YujNpvrEmPAX2pg/viewform",
    infoURL: "https://docs.celo.org/",
  },
  "73799": {
    name: "Energy Web Volta Testnet",
    chainID: 73799,
    shortName: "vt",
    chain: "Volta",
    network: "testnet",
    networkId: 73799,
    symbol: "VT",
    decimals: 18,
    rpc: "https://volta-rpc.energyweb.org",
    explorer: "",
    faucets: "https://voltafaucet.energyweb.org",
    infoURL: "https://energyweb.org",
  },
  "78110": {
    name: "Firenze test network",
    chainID: 78110,
    shortName: "firenze",
    chain: "ETH",
    network: "testnet",
    networkId: 78110,
    symbol: "FIN",
    decimals: 18,
    rpc: "https://ethnode.primusmoney.com/firenze",
    explorer: "",
    faucets: "",
    infoURL: "https://primusmoney.com",
  },
  "80001": {
    name: "Matic Testnet Mumbai",
    chainID: 80001,
    shortName: "maticmum",
    chain: "Matic",
    network: "testnet",
    networkId: 80001,
    symbol: "tMATIC",
    decimals: 18,
    rpc: "https://rpc-mumbai.matic.today",
    explorer: "",
    faucets: "https://faucet.matic.network/",
    infoURL: "https://matic.network/",
  },
  "200625": {
    name: "Akroma",
    chainID: 200625,
    shortName: "aka",
    chain: "AKA",
    network: "mainnet",
    networkId: 200625,
    symbol: "AKA",
    decimals: 18,
    rpc: "https://remote.akroma.io",
    explorer: "",
    faucets: "",
    infoURL: "https://akroma.io",
  },
  "246529": {
    name: "ARTIS sigma1",
    chainID: 246529,
    shortName: "ats",
    chain: "ARTIS",
    network: "sigma1",
    networkId: 246529,
    symbol: "ATS",
    decimals: 18,
    rpc: "https://rpc.sigma1.artis.network",
    explorer: "",
    faucets: "",
    infoURL: "https://artis.eco",
  },
  "246785": {
    name: "ARTIS Testnet tau1",
    chainID: 246785,
    shortName: "atstau",
    chain: "ARTIS",
    network: "tau1",
    networkId: 246785,
    symbol: "tATS",
    decimals: 18,
    rpc: "https://rpc.tau1.artis.network",
    explorer: "",
    faucets: "",
    infoURL: "https://artis.network",
  },
  "421611": {
    name: "Arbitrum Testnet Rinkeby",
    chainID: 421611,
    shortName: "arb-rinkeby",
    chain: "ETH",
    network: "rinkeby",
    networkId: 421611,
    symbol: "ARETH",
    decimals: 18,
    rpc: "https://rinkeby.arbitrum.io/rpc",
    explorer: "",
    faucets: "",
    infoURL: "https://arbitrum.io",
  },
  "1313114": {
    name: "Ether-1",
    chainID: 1313114,
    shortName: "etho",
    chain: "ETHO",
    network: "mainnet",
    networkId: 1313114,
    symbol: "ETHO",
    decimals: 18,
    rpc: "https://rpc.ether1.org",
    explorer: "",
    faucets: "",
    infoURL: "https://ether1.org",
  },
  "1313500": {
    name: "Xerom",
    chainID: 1313500,
    shortName: "xero",
    chain: "XERO",
    network: "mainnet",
    networkId: 1313500,
    symbol: "XERO",
    decimals: 18,
    rpc: "https://rpc.xerom.org",
    explorer: "",
    faucets: "",
    infoURL: "https://xerom.org",
  },
  "7762959": {
    name: "Musicoin",
    chainID: 7762959,
    shortName: "music",
    chain: "MUSIC",
    network: "mainnet",
    networkId: 7762959,
    symbol: "MUSIC",
    decimals: 18,
    rpc: "https://mewapi.musicoin.tw",
    explorer: "",
    faucets: "",
    infoURL: "https://musicoin.tw",
  },
  "13371337": {
    name: "PepChain Churchill",
    chainID: 13371337,
    shortName: "tpep",
    chain: "PEP",
    network: "testnet",
    networkId: 13371337,
    symbol: "TPEP",
    decimals: 18,
    rpc: "https://churchill-rpc.pepchain.io",
    explorer: "",
    faucets: "",
    infoURL: "https://pepchain.io",
  },
  "18289463": {
    name: "IOLite",
    chainID: 18289463,
    shortName: "ilt",
    chain: "ILT",
    network: "mainnet",
    networkId: 18289463,
    symbol: "ILT",
    decimals: 18,
    rpc: "https://net.iolite.io",
    explorer: "",
    faucets: "",
    infoURL: "https://iolite.io",
  },
  "20181205": {
    name: "quarkblockchain",
    chainID: 20181205,
    shortName: "qki",
    chain: "QKI",
    network: "mainnet",
    networkId: 20181205,
    symbol: "QKI",
    decimals: 18,
    rpc: "https://hz.rpc.qkiscan.cn",
    explorer: "",
    faucets: "",
    infoURL: "https://quarkblockchain.org/",
  },
  "28945486": {
    name: "Auxilium Network Mainnet",
    chainID: 28945486,
    shortName: "auxi",
    chain: "AUX",
    network: "mainnet",
    networkId: 28945486,
    symbol: "AUX",
    decimals: 18,
    rpc: "https://rpc.auxilium.global",
    explorer: "",
    faucets: "",
    infoURL: "https://auxilium.global",
  },
  "35855456": {
    name: "Joys Digital Mainnet",
    chainID: 35855456,
    shortName: "JOYS",
    chain: "JOYS",
    network: "mainnet",
    networkId: 35855456,
    symbol: "JOYS",
    decimals: 18,
    rpc: "https://node.joys.digital",
    explorer: "",
    faucets: "",
    infoURL: "https://joys.digital",
  },
  "61717561": {
    name: "Aquachain",
    chainID: 61717561,
    shortName: "aqua",
    chain: "AQUA",
    network: "mainnet",
    networkId: 61717561,
    symbol: "AQUA",
    decimals: 18,
    rpc: "https://c.onical.org",
    explorer: "",
    faucets: "https://aquacha.in/faucet",
    infoURL: "https://aquachain.github.io",
  },
  "99415706": {
    name: "Joys Digital TestNet",
    chainID: 99415706,
    shortName: "TOYS",
    chain: "TOYS",
    network: "testnet",
    networkId: 99415706,
    symbol: "TOYS",
    decimals: 18,
    rpc: "https://toys.joys.cash/",
    explorer: "",
    faucets: "https://faucet.joys.digital/",
    infoURL: "https://joys.digital",
  },
  "1122334455": {
    name: "IPOS Network",
    chainID: 1122334455,
    shortName: "ipos",
    chain: "IPOS",
    network: "mainnet",
    networkId: 1122334455,
    symbol: "IPOS",
    decimals: 18,
    rpc: "https://rpc.iposlab.com",
    explorer: "",
    faucets: "",
    infoURL: "https://iposlab.com",
  },
  "1313161554": {
    name: "Aurora MainNet",
    chainID: 1313161554,
    shortName: "aurora",
    chain: "NEAR",
    network: "mainnet",
    networkId: 1313161554,
    symbol: "aETH",
    decimals: 18,
    rpc: "https://rpc.mainnet.aurora.dev:8545",
    explorer: "",
    faucets: "",
    infoURL: "https://aurora.dev",
  },
  "1313161555": {
    name: "Aurora TestNet",
    chainID: 1313161555,
    shortName: "aurora-testnet",
    chain: "NEAR",
    network: "testnet",
    networkId: 1313161555,
    symbol: "aETH",
    decimals: 18,
    rpc: "https://rpc.testnet.aurora.dev:8545",
    explorer: "",
    faucets: "",
    infoURL: "https://aurora.dev",
  },
  "1313161556": {
    name: "Aurora BetaNet",
    chainID: 1313161556,
    shortName: "aurora-betanet",
    chain: "NEAR",
    network: "betanet",
    networkId: 1313161556,
    symbol: "aETH",
    decimals: 18,
    rpc: "https://rpc.betanet.aurora.dev:8545",
    explorer: "",
    faucets: "",
    infoURL: "https://aurora.dev",
  },
  "1666600000": {
    name: "Harmony Mainnet Shard 0",
    chainID: 1666600000,
    shortName: "hmy-s0",
    chain: "Harmony",
    network: "mainnet",
    networkId: 1666600000,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://api.harmony.one",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666600001": {
    name: "Harmony Mainnet Shard 1",
    chainID: 1666600001,
    shortName: "hmy-s1",
    chain: "Harmony",
    network: "mainnet",
    networkId: 1666600001,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://s1.api.harmony.one",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666600002": {
    name: "Harmony Mainnet Shard 2",
    chainID: 1666600002,
    shortName: "hmy-s2",
    chain: "Harmony",
    network: "mainnet",
    networkId: 1666600002,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://s2.api.harmony.one",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666600003": {
    name: "Harmony Mainnet Shard 3",
    chainID: 1666600003,
    shortName: "hmy-s3",
    chain: "Harmony",
    network: "mainnet",
    networkId: 1666600003,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://s3.api.harmony.one",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666700000": {
    name: "Harmony Testnet Shard 0",
    chainID: 1666700000,
    shortName: "hmy-b-s0",
    chain: "Harmony",
    network: "testnet",
    networkId: 1666700000,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://api.s0.b.hmny.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666700001": {
    name: "Harmony Testnet Shard 1",
    chainID: 1666700001,
    shortName: "hmy-b-s1",
    chain: "Harmony",
    network: "testnet",
    networkId: 1666700001,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://api.s1.b.hmny.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666700002": {
    name: "Harmony Testnet Shard 2",
    chainID: 1666700002,
    shortName: "hmy-b-s2",
    chain: "Harmony",
    network: "testnet",
    networkId: 1666700002,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://api.s2.b.hmny.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "1666700003": {
    name: "Harmony Testnet Shard 3",
    chainID: 1666700003,
    shortName: "hmy-b-s3",
    chain: "Harmony",
    network: "testnet",
    networkId: 1666700003,
    symbol: "ONE",
    decimals: 18,
    rpc: "https://api.s3.b.hmny.io",
    explorer: "",
    faucets: "",
    infoURL: "https://www.harmony.one/",
  },
  "3125659152": {
    name: "Pirl",
    chainID: 3125659152,
    shortName: "pirl",
    chain: "PIRL",
    network: "mainnet",
    networkId: 3125659152,
    symbol: "PIRL",
    decimals: 18,
    rpc: "https://wallrpc.pirl.io",
    explorer: "",
    faucets: "",
    infoURL: "https://pirl.io",
  },
};
